# Generated by Django 3.2.16 on 2023-02-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20230210_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
