# Generated by Django 3.2.16 on 2023-02-10 22:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_rename_urls_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urls_data',
            field=jsonfield.fields.JSONField(default='default_urls'),
        ),
    ]
