# Generated by Django 3.2.16 on 2023-02-11 19:55

from django.db import migrations, models
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_url_urls_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urls_data',
            field=models.JSONField(default=scraping.models.default_urls),
        ),
    ]
