# Generated by Django 4.1.6 on 2023-02-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_vacancies_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urls_data',
            new_name='url_data',
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='scraping.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='company',
            field=models.CharField(max_length=250, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок вакансии'),
        ),
    ]
